### ISSUE TITLE
[Help] Create Rss feed for a specific Wikipedia Article.

### ISSUE THREAD

**Issue by bambirombi** [clokep/to-rss#149]
I am a newbie and this is being a pain...
For example, I choose this wikipedia link: https://en.wikipedia.org/wiki/Category:Libertarian_historians
I transform to this feed: http://en.wikipedia.org/w/index.php?title=Category:Libertarian_historians&action=history&feed=rss
But, when I open it in newsboat it only retrieves one feed and it is not what I want.

I want to receive updates of that link, so if an author is added, I could know that it has been added. And when opening the feed in the browser I would like to be redirected to the author's page, not the revision page...

**Comment by clokep** [comment]
> I transform to this feed: http://en.wikipedia.org/w/index.php?title=Category:Libertarian_historians&action=history&feed=rss

This seems to be the history of the page itself, while I think you're looking for an RSS feed for changes to a category (e.g. when articles are added or removed from a category)? Is that accurate? I have no idea if that's possible in MediaWiki, sorry.

That seems to be described at https://en.wikipedia.org/wiki/Help:Category#Watching_category_additions_and_removals, however.

And messing with the URL it provides I think https://en.wikipedia.org/w/api.php?hidebots=1&hidecategorization=1&hideWikibase=1&urlversion=1&days=7&limit=50&target=Category%3ALibertarian_historians&action=feedrecentchanges&feedformat=rss might do what you want?

**Comment by clokep** [comment]
I think you'll need to open bugs against MediaWiki for those features then, it doesn't really fit into this project. Sorry!

**Comment by bambirombi** [comment]
No problem.
Well, I have tried another wikipedia category, and it gives me more feeds. It appears that the feeds are limited to seven days? So maybe that is the reason why in the other category I only saw one feed. If for whatever reason some day you figure out how to increase that time limit to have more feeds, let me know.

and thanks! It is better than  what I had.

**Comment by clokep** [comment]
@bambirombi There's a `days` parameter in the URL, e.g. for 30 days: https://en.wikipedia.org/w/api.php?hidebots=1&hidecategorization=1&hideWikibase=1&urlversion=1&days=30&limit=50&target=Category%3ALibertarian_historians&action=feedrecentchanges&feedformat=rss

That seems to have more entries in it.

**Comment by bambirombi** [comment]
Thanks!
