### ISSUE TITLE
[Feature Request] Wikipedia Current Events as 'Headline' News Items

### ISSUE THREAD

**Issue by Spottyfriend** [clokep/to-rss#158]
I use a personalised news aggregator that operates using RSS feeds. I'd like to import the Wikipedia Current Events page into my aggregator, but when imported the RSS feed you have made for it only shows a list of dates that links to the current events page for that day (see below). Would it be possible to alter the feed so that it shows the 'headlines' for the day, rather than simply giving a link to the day's page? This is almost possible using https://politepol.com/ but it's not quite intelligent enough to detect all the right text.

![image](https://user-images.githubusercontent.com/50644325/194581118-c0b82c17-0349-40f0-89b9-d5ae580788b8.png)

This may not be possible since I really know nothing about coding etc, and if so I apologise for the hassle, but I thought it might be worth asking anyway. Many thanks!

**Comment by clokep** [comment]
Sorry for the delay in responding. I'm not really sure what you're requesting though -- are you suggesting having (essentially) each bullet point as a separate article or something like that? (What do you mean by "headlines"?)

**Comment by clokep** [comment]
> I don't find a feed that simply links to the current events page for that date particularly useful as an RSS feed for news (since it's almost as easy as navigating there), although I may well not be the average user!

I have no idea who other users are, I built this for myself. I wanted a way to read that article daily *without having to navigate there* (or remember to navigate there).

> I assumed that, intuitively, the feed would display the news items listed on the current events Wikipedia page, a la an RSS feed from other news sources
>
> I'm not sure it's a possible thing to implement since I am a noob when it comes to these things!

I think that it wouldn't be too awful, it is essentially finding all external links on the page and then adding an entry for it. This is very much not what this was designed for, which was to be a summary feed of news, and if there are interesting articels you can easily jump to the source via the embedded link.

**Comment by Spottyfriend** [comment]
> This is very much not what this was designed for, which was to be a summary feed of news.

That's interesting. I appreciate that you made this for yourself, but I would tentatively suggest that:
- Current events: 2022-10-25
- Current events: 2022-10-24
- Current events: 2022-10-23
- Current events: 2022-10-22

is not a particularly useful summary feed of news.

Whereas, something like:
- Israeli soldiers raid a Lions' Den headquarter in Nablus, in the West Bank, killing three militants, including one of the group's founders.
- A young woman attempts to shoot the Presidential Security Force of Indonesia and/or President of Indonesia Joko Widodo at the Istana Negara in Central Jakarta, before being arrested.
- More than 30 people are killed and another 15 are missing after tribal clashes between the Kulumata and Kuboma on Kiriwina Island in Milne Bay Province, Papua New Guinea.
- Adidas and Def Jam Recordings terminate their respective Yeezy and GOOD Music partnerships with rapper Kanye West following multiple remarks perceived as anti-semitic.

is a _more_ useful summary feed of news, and is more similar to other news RSS feeds.

If that's not the aim of the project then obviously that's all good, but just to clarify. And now I'll stop bothering you!

**Comment by clokep** [comment]
> is a _more_ useful summary feed of news, and is more similar to other news RSS feeds.

Maybe, but I don't think there's a 1-to-1 correlation of bullet points in the Wikipedia pages and news articles (and some bullet points actually reference multiple news articles). This doesn't seem easily solved.
